# Generated by Django 5.0.6 on 2024-07-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus, culpa mollitia nobis obcaecati sit ex. Molestiae eaque dolores, sapiente dolorem rem placeat quae quas praesentium consequatur explicabo cum...')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recetas')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
